# Generated by Django 3.2.12 on 2022-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_license_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
