# Generated by Django 3.2.12 on 2022-03-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_license_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='education',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='job',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='name',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='phone',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
