# Generated by Django 3.2.12 on 2022-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220331_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='education',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='job',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
