# Generated by Django 3.2.12 on 2022-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220331_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='phone',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
