# Generated by Django 3.2.12 on 2022-02-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Payment',
        ),
    ]
