# Generated by Django 3.2.12 on 2022-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20220214_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
